[package]
name = "HUI"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2"
#lazy_static = "1.4"  # for callbacks workaround

#[build-dependencies]
#cc = "1.0" # if building the C code from source (not implemented)
