name: Build HUI

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build-linux-gtk3:
    name: Build Linux GTK3 x64
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x ./build_linux_gtk3.sh
          sudo apt update
          ./build_linux_gtk3.sh --dependencies --deploy --tests
          BUILD_DIR=$(ls -d HUI-linux-*)
          tar -czvf $BUILD_DIR.tar.gz $BUILD_DIR

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-gtk3-build
          path: HUI-linux-*.tar.gz

  build-win-cef:
    name: Build Windows CEF x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure 7-Zip is installed
        run: |
          choco install 7zip -y
        shell: cmd

      - name: Install dependencies and build
        run: ./build_win_cef.bat --dependencies --deploy --tests

      - name: Archive build artifacts
        run: |
          FOR /D %%G IN (HUI-win-*) DO (
              tar -czvf %%G.tar.gz %%G
          )

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-cef-build
          path: HUI-win-*.tar.gz
